# Book settings
title: "rudof: A semantic-less tool for the Semantic Web"
author: Jose Emilio Labra Gayo and rudof maintainers
copyright: "2026, rudof project"
description: A Jupyter book that introduces Knowledge Graphs concepts using rudof
logo: logo.svg

launch_buttons:
  colab_url: "https://colab.research.google.com"


execute:
  execute_notebooks: force
  timeout: 300
  only_build_toc_files: true

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/rudof-project/tutorials
  path_to_book: rudof
  branch: main

html:
  use_issues_button: true
  use_repository_button: true
