@startuml
hide empty members
top to bottom direction
skinparam linetype polyline
hide circles
skinparam shadowing true
skinparam class {
 BorderColor Black
 ArrowColor Black
}
class "ex:Company" as 2 <<(S,#FF7700)>> [[http://example.org/Company ex:Company]] { 
[[http://example.org/name ex:name]] : .  
--
}
class "ex:Person" as 1 <<(S,#FF7700)>> [[http://example.org/Person ex:Person]] { 
[[http://example.org/name ex:name]] : .  
--
[[http://example.org/birthdate ex:birthdate]] : . ?
--
}
1 --> "*" 2 : [[http://example.org/worksFor ex:worksFor]]
2 --> "*" 1 : [[http://example.org/employee ex:employee]]
@enduml
